### ISSUE TITLE
gitversionview output not longer fits on status bar

### ISSUE THREAD

**Issue by wardy3** [HSSE-Dev/GitVersionView#3]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/15006782/69108654-71130e80-0ac9-11ea-9ead-a1401f945246.png">

until recently this worked fine but now it seems to be slightly bigger than the space allowed.

pressing the (i) button pops up a window where it's perfectly readable

**Comment by HSSE-Dev** [comment]
Hello, many thanks for the message and apologies for the late response. The problem also occurs with me and I will try to look at it as soon as possible.

**Comment by wardy3** [comment]
Hi, I just had a quick play with the extension

Looks like the trailing space is making it wrap in VSCode

So, I changed line 

```
this.statusBarItemText = `$(info) GitVersion:  ${version} `;
```
to
```
this.statusBarItemText = `$(info) GitVersion:  ${version}`;
```

**Comment by HSSE-Dev** [comment]
@wardy3 sorry i had forgotten to fix it. Extension fix is online. Thanks for help
